# Use a base image with Java 17
FROM openjdk:17-jdk-slim

# Set working directory
WORKDIR /app

# Copy JAR file
COPY target/User_Service-0.0.1-SNAPSHOT.jar app.jar


# Run the jar file
ENTRYPOINT ["java", "-jar", "app.jar"]